name: Tests

on:

  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:

  node-unit-tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Current LTS version: v14
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: grunt test
      - name: Coveralls Parallel
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          flag-name: node-${{ matrix.node-version }}
          path-to-lcov: coverage/lcov.info
          parallel: true


  finish:
    needs:
      - node-unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Coveralls Finished
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.github_token }}
          parallel-finished: true
